# Generated by Django 3.1.8 on 2023-04-10 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drone_recon', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='tutorial_completed',
        ),
        migrations.RemoveField(
            model_name='trial',
            name='reward_probs_record',
        ),
        migrations.AddField(
            model_name='trial',
            name='feedback_given',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='trial',
            name='trial_number',
            field=models.IntegerField(default=None),
        ),
    ]
