# Generated by Django 3.1.8 on 2023-04-10 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drone_recon', '0002_auto_20230410_0145'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trial',
            old_name='reward',
            new_name='correct',
        ),
        migrations.RemoveField(
            model_name='trial',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='trial',
            name='start_time',
        ),
        migrations.AddField(
            model_name='trial',
            name='correct_class',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='trial',
            name='rt',
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='trial',
            name='response',
            field=models.CharField(default='', max_length=100),
        ),
    ]
