# Generated by Django 3.1.8 on 2023-04-10 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drone_recon', '0003_auto_20230410_0232'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trial',
            old_name='rt',
            new_name='rt_classification',
        ),
        migrations.AddField(
            model_name='trial',
            name='rt_confidence',
            field=models.IntegerField(default=None),
        ),
    ]
