# Generated by Django 3.1.8 on 2023-05-27 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drone_recon', '0006_auto_20230410_1354'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='browser',
            field=models.CharField(default='', max_length=200),
        ),
    ]
