# Generated by Django 3.1.8 on 2023-08-25 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drone_recon', '0007_session_browser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stimulus',
            name='name',
            field=models.CharField(max_length=300),
        ),
    ]
